### PR TITLE
Added bootstrap form layout support ...

### PR DESCRIPTION
**Pull request by maxatbrs**
We are using this project as a part of our production level Angular app. Love the setup but it does have two things we didn't like about it:
 - Issue #39 | All input attribute were being applied to the label and not the input element
 - Issue #40 | No bootstrap support

By wrapping elements the divs and corresponding  bootstrap classes, I was able to successfully get this to work. What do you think?

### CODE REVIEW

**Comment by danhunsaker** [comment]
This is a Bootstrap-specific change.  I'd prefer something more flexible, allowing HTML micro-templates to be provided for each control type, instead of hard-coding a single layout.  It'll need a hard-coded fallback, but otherwise...  Then we just include some micro-template collections for each of the major UIs (including Bootstrap) and let the user include the appropriate ones as needed.

**Comment by TroyWolf** [comment]
maxatbrs, I found this thread looking for how I might be able to wrap my form elements in a <div> that includes Bootstrap class(es). While I understand danhunsaker's desire for a generic solution, I am very interested in your changes now. How do I take advantage of the work you've done?

danhunsaker, in the interim, would it be possible to take the work maxatbrs has done to "Boostrapize" your project and make it a config thing? So you get your solution without the Bootstrap wrapping or flip a switch and get things Bootstrapped. Possible?

**Comment by TroyWolf** [comment]
The Angular-Formly project seems to do everything I wanted angular-dynforms for and a WHOLE lot more including templates (Bootstrap and others), custom templates, loading templates via HTTP, etc.
http://angular-formly.com/

**Comment by danhunsaker** [comment]
I listed a whole bunch of alternatives at the bottom of the README.  I'll try to remember to add this one at some point.

**Pull request closed without merging**
